---

# Playbook is used to fill csv table with data about network connections
- name: Fill csv file with data
  connection: local
  gather_facts: yes
  hosts: localhost
  tasks: 
    #- name: Add module for pytest_ansible
    #  shell: export ANSIBLE_LIBRARY=./
    #  become: True
    - debug:
        msg: "{{ method_name }}"
      
    # Importig role - to use tags inside
    - import_role: 
        name: fill_csv
      tags: csv